services:
    nginx:
        build: conf.d
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf           
        restart: unless-stopped
        ports:
            - 8083:81
        networks:
            - ts      

    #memcached

    app-ted:
        build: .
        container_name: "tedsearch"
        ports: 
            - 8084:9191
        networks: 
            - ts   
    
networks: 
    ts: