services:
    ted_nginx:
        image: 644435390668.dkr.ecr.us-east-1.amazonaws.com/nobel_ted_nginx:latest
        container_name: "nginx-proxy"          
        restart: unless-stopped
        ports:
            - "8083:81"
        networks:
            - ts    

    #memcached

    ted_search:
        image: 644435390668.dkr.ecr.us-east-1.amazonaws.com/nobel_tedsearch:latest
        container_name: "tedsearch"
        ports: 
            - "8084:9191"
        networks: 
            - ts   
    
networks: 
    ts: